<header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="index.php" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <img src="img/logo.svg" alt="Shwitter" height="50px" />
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <!--
                <li><a href="#" class="nav-link px-2 link-secondary">Overview</a></li>
                -->
            </ul>

            <div class="text-end">
                <a href="index.php?ctrl=connexion" class="btn btn-outline-primary me-2">Connexion</a>
                <a href="index.php?ctrl=inscription" class="btn btn-primary">S'inscrire</a>
            </div>
        </div>
    </div>
</header>