<!doctype html>
<html>

<head>
    <?php require_once 'section/head.phtml' ?>
    <title>Shwitter</title>
</head>

<body>
    <?php require_once 'section/entete.phtml'; ?>

    <section id="contenu">
        <div class="container">
            <?php require_once 'section/retroaction.phtml'; ?>
            <p>Page d'accueil...</p>
            <p>Dans mon souvenir, je m'étais basé sur <a href="https://www.bootdey.com/snippets/view/profile-with-data-and-skills" target="_blank">ce template Bootstrap.</a></p>
            <p>Une simple recherche Google pourrait aussi vous permettre de trouver d'autres templates gratuits : <a href="https://www.google.com/search?q=free+Bootstrap+templates" target="_blank">free Bootstrap templates</a> + mot_clef</p>
            <p>L'utilisation de Bootstrap est facultative! Vous pouvez faire du "pur" html/css sans problème!</p>
        </div>
    </section>

    <?php require_once 'section/pied.phtml'; ?>
</body>

</html>