<!doctype html>
<html>

<head>
    <?php require_once 'section/head.phtml' ?>
    <title>Shwitter</title>
</head>

<body>
    <?php require_once 'section/entete.phtml'; ?>


    <section id="contenu">
        <div class="container">

            <div class="row">
                <div class="col-md-4 mb30">
                    <div class="card">
                        <div class="card-content pt20 pb20 profile-header">
                            <img src="<?= $utilisateur->getUrlAvatar() ?>" alt="N.D." class="img-fluid rounded-circle">
                            <h4 class="card-title text-center mb20"><?= $utilisateur->getNomUtilisateur() ?></h4>
                            <p><?= $utilisateur->getBio() ?></p>
                            <hr>
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>
                                            <strong>LOCALISATION:</strong>
                                        </td>
                                        <td>
                                            <p class="text-muted mb-0"><?= $utilisateur->getLocalisation() ?></p>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <strong>A REJOINT LE:</strong>
                                        </td>
                                        <td>
                                            <p class="text-muted mb-0"><?= $utilisateur->getDateCreation()->format('Y-m-d') ?></p>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 mb30">
                    <?php if (isset($utilisateurConnecte) && ($utilisateurConnecte->getId() === $utilisateur->getId())) : ?>
                        <form id="formulaire-shweetter" method="post" action="index.php">
                            <div class="post-editor">
                                <textarea name="texte" id="textarea-texte" class="post-field" placeholder="Écris un Shweet!" maxlength="255"></textarea>
                                <div>
                                    <p id="erreur-texte" class="erreur"><?php require_once 'section/retroaction.phtml'; ?></p>
                                </div>

                                <div class="d-flex">
                                    <input type="hidden" name="ctrl" value="shweet">
                                    <input type="hidden" name="action" value="shweetter">
                                    <button class="btn btn-success px-4 py-1">Shwitter!!!</button>
                                </div>
                            </div>
                        </form>
                    <?php endif; ?>
                    <div class="card">
                        <div>
                            <div class="post-content">
                                <?php if (empty($shweets)) : ?>
                                    <p>Aucun Shweet...</p>
                                <?php else : ?>
                                    <?php foreach ($shweets as $shweet) : ?>
                                        <div class="card">
                                            <div id="<?= $shweet->getId() ?>" class="post-container">
                                                <img src="<?= $shweet->getAuteur()->getUrlAvatar() ?>" alt="N.D." class="profile-photo-md pull-left">

                                                <div class="post-detail">
                                                    <div class="user-info">
                                                        <h5>
                                                            <a class="profile-link" href="index.php?ctrl=default&action=afficherProfil&id=<?= $shweet->getAuteur()->getId() ?>"><?= $shweet->getAuteur()->getNomUtilisateur() ?></a>
                                                        </h5>
                                                        <p class="text-muted">Publié le <?= $shweet->getDateCreation()->format('Y-m-d') ?> à <?= $shweet->getDateCreation()->format('H:i:s') ?></p>
                                                    </div>
                                                    <div class="line-divider"></div>
                                                    <div class="post-text">
                                                        <p><?= htmlspecialchars($shweet->getTexte()) ?></p>
                                                        <?php if (isset($utilisateurConnecte) && $utilisateurConnecte->getId() === $shweet->getAuteurId()) : ?>
                                                            <form method="post" action="index.php">
                                                                <div class="dropdown">
                                                                    <button class="dropdown-toggle py-0 btn-menu" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                                                        ...
                                                                    </button>
                                                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                                                        <li><input type="submit" class="btn btn-link" value="Supprimer"></li>
                                                                    </ul>
                                                                </div>
                                                                <input type="hidden" name="shweet-id" value="<?= $shweet->getId() ?>">
                                                                <input type="hidden" name="ctrl" value="shweet">
                                                                <input type="hidden" name="action" value="supprimer">
                                                                <input type="hidden" name="profil-origine-id" value="<?= $utilisateurConnecte->getId() ?>">
                                                            </form>
                                                        <?php endif; ?>
                                                    </div>
                                                    <div class="line-divider"></div>
                                                    <?php foreach ($shweet->getEnfants() as $enfant) : ?>
                                                        <div id="<?= $enfant->getId() ?>" class="post-comment">
                                                            <img src="<?= $enfant->getAuteur()->getUrlAvatar() ?>" alt="N.D." class="profile-photo-sm">
                                                            <p>
                                                                <a href="index.php?ctrl=default&action=afficherProfil&id=<?= $enfant->getAuteur()->getId() ?>" class="profile-link"><?= $enfant->getAuteur()->getNomUtilisateur() ?></a>
                                                                <?= $enfant->getTexte() ?>
                                                            </p>
                                                            <?php if (isset($utilisateurConnecte) && $utilisateurConnecte->getId() == $enfant->getAuteurId()) : ?>
                                                                <form method="post" action="index.php">
                                                                    <div class="dropdown">
                                                                        <button class="dropdown-toggle py-0 btn-menu" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                                                            ...
                                                                        </button>
                                                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                                                            <li><input type="submit" class="btn btn-link" value="Supprimer"></li>
                                                                        </ul>
                                                                    </div>
                                                                    <input type="hidden" name="shweet-id" value="<?= $enfant->getId() ?>">
                                                                    <input type="hidden" name="ctrl" value="shweet">
                                                                    <input type="hidden" name="action" value="supprimer">
                                                                    <input type="hidden" name="profil-origine-id" value="<?= $shweet->getAuteurId() ?>">
                                                                </form>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endforeach; ?>
                                                    <?php if (isset($utilisateurConnecte)) : ?>
                                                        <form class="comment-form" method="post" action="index.php">
                                                            <div class="post-comment">
                                                                <img src="<?= $utilisateurConnecte->getUrlAvatar() ?>" alt="N.D." class="profile-photo-sm">

                                                                <input id="input-texte-33" type="text" class="form-control" name="texte" placeholder="Répondre..." maxlength="255">

                                                                <div>
                                                                    <p id="erreur-texte-33" class="erreur"><?php require_once 'section/retroaction.phtml'; ?></p>
                                                                </div>

                                                                <input type="hidden" name="parent-id" value="<?= $shweet->getId() ?>">
                                                                <input type="hidden" name="ctrl" value="shweet">
                                                                <input type="hidden" name="action" value="commenter">
                                                                <input type="hidden" name="profil-origine-id" value="<?= $utilisateurConnecte->getId() ?>">
                                                            </div>
                                                        </form>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <br>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <?php require_once 'section/pied.phtml'; ?>
</body>

</html>